# Generated by Django 5.2.8 on 2025-11-24 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=10)),
                ('farm_type', models.CharField(choices=[('organic', 'Organic'), ('conventional', 'Conventional'), ('hydroponic', 'Hydroponic'), ('greenhouse', 'Greenhouse')], default='conventional', max_length=20)),
                ('soil_type', models.CharField(max_length=100)),
                ('established_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
                'db_table': 'farm_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('soybean', 'Soybean'), ('rice', 'Rice'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits')], max_length=20)),
                ('crop_variety', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=8)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('location_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('irrigation_system', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='monitoring.farmprofile')),
            ],
            options={
                'verbose_name': 'Field Plot',
                'verbose_name_plural': 'Field Plots',
                'db_table': 'field_plot',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('moisture_drop', 'Soil Moisture Drop'), ('temperature_spike', 'Temperature Spike'), ('humidity_anomaly', 'Humidity Anomaly'), ('ph_imbalance', 'pH Imbalance'), ('nutrient_deficiency', 'Nutrient Deficiency'), ('pest_infestation', 'Pest Infestation'), ('disease_detection', 'Disease Detection')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('detected_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('normal_range_min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('normal_range_max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('model_confidence', models.DecimalField(decimal_places=3, help_text='Confidence score from 0 to 1', max_digits=5)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='monitoring.fieldplot')),
            ],
            options={
                'verbose_name': 'Anomaly Event',
                'verbose_name_plural': 'Anomaly Events',
                'db_table': 'anomaly_event',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('yield_amount', models.DecimalField(decimal_places=2, help_text='Yield in kg', max_digits=10)),
                ('quality_rating', models.PositiveIntegerField(help_text='Quality rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='monitoring.fieldplot')),
            ],
            options={
                'verbose_name': 'Harvest Record',
                'verbose_name_plural': 'Harvest Records',
                'db_table': 'harvest_record',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_type', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler System'), ('flood', 'Flood Irrigation'), ('manual', 'Manual Watering')], max_length=20)),
                ('water_volume', models.DecimalField(decimal_places=2, help_text='Water volume in liters', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('irrigated_at', models.DateTimeField()),
                ('moisture_before', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('moisture_after', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_logs', to='monitoring.fieldplot')),
            ],
            options={
                'verbose_name': 'Irrigation Log',
                'verbose_name_plural': 'Irrigation Logs',
                'db_table': 'irrigation_log',
                'ordering': ['-irrigated_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil Moisture'), ('temperature', 'Air Temperature'), ('humidity', 'Humidity'), ('ph', 'pH Level'), ('nitrogen', 'Nitrogen Level')], max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(choices=[('percentage', '%'), ('celsius', '°C'), ('fahrenheit', '°F'), ('ph', 'pH'), ('ppm', 'PPM')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_id', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='monitoring.fieldplot')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_reading',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, help_text='Rainfall in mm', max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('solar_radiation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='monitoring.fieldplot')),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'db_table': 'weather_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(choices=[('irrigation', 'Adjust Irrigation'), ('fertilization', 'Apply Fertilizer'), ('pest_control', 'Pest Control'), ('disease_treatment', 'Disease Treatment'), ('harvest', 'Schedule Harvest'), ('monitoring', 'Increase Monitoring'), ('consultation', 'Consult Expert')], max_length=50)),
                ('action_details', models.TextField()),
                ('explanation_text', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('anomaly_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='monitoring.anomalyevent')),
            ],
            options={
                'verbose_name': 'Agent Recommendation',
                'verbose_name_plural': 'Agent Recommendations',
                'db_table': 'agent_recommendation',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['anomaly_event'], name='agent_recom_anomaly_4d4499_idx'), models.Index(fields=['is_implemented'], name='agent_recom_is_impl_b558a4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='farmprofile',
            index=models.Index(fields=['name'], name='farm_profil_name_8b08a9_idx'),
        ),
        migrations.AddIndex(
            model_name='farmprofile',
            index=models.Index(fields=['owner'], name='farm_profil_owner_i_781bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['farm', 'name'], name='field_plot_farm_id_4dc3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['crop_type'], name='field_plot_crop_ty_3dc3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['plot', 'detected_at'], name='anomaly_eve_plot_id_82cf03_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['severity', 'is_resolved'], name='anomaly_eve_severit_0634a1_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['anomaly_type'], name='anomaly_eve_anomaly_7a8ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestrecord',
            index=models.Index(fields=['plot', 'harvest_date'], name='harvest_rec_plot_id_6dd1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='irrigationlog',
            index=models.Index(fields=['plot', 'irrigated_at'], name='irrigation__plot_id_d7fa25_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['plot', 'timestamp'], name='sensor_read_plot_id_d0feb0_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor_type', 'timestamp'], name='sensor_read_sensor__5f61a7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='sensor_read_timesta_7dba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['plot', 'timestamp'], name='weather_dat_plot_id_26ab73_idx'),
        ),
    ]
