# Generated by Django 5.2.8 on 2025-12-14 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('soil_moisture', 'Soil Moisture'), ('ph_level', 'pH Level'), ('light_intensity', 'Light Intensity')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('current_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=100)),
                ('size', models.FloatField(help_text='Size in hectares')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='sensor_read_plot_id_d0feb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='sensor_read_sensor__5f61a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='sensor_read_timesta_7dba3a_idx',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='sensor_id',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)'), ('soil_moisture', 'Soil Moisture (%)'), ('ph_level', 'pH Level'), ('light_intensity', 'Light Intensity (lux)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='sensorreading',
            table=None,
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitoring.alert'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.plot'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='monitoring.plot'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['plot', 'sensor_type', '-timestamp'], name='monitoring__plot_id_498f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['plot', '-timestamp'], name='monitoring__plot_id_d20ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', '-timestamp'], name='monitoring__severit_fe526f_idx'),
        ),
    ]
